export const siteUrl = "https://barakovaluxurytravel.com";
export const siteName = "Barakova Luxury Travel";
export const contactEmail = "info@barakovaluxurytravel.com";
export const contactEmailHref = `mailto:${contactEmail}`;
export const resendFromEmailDefault = `Barakova Luxury Travel <${contactEmail}>`;
export const contactPhone = "+359883770909";
export const contactPhoneDisplay = "0883 770 909";
export const contactPhoneHref = `tel:${contactPhone}`;
export const contactWhatsAppHref = "https://wa.me/359883770909";
